dist: trusty
sudo: false

language: node_js
node_js:
  - "8"

install:
  - npm install
	
jobs:
  fast_finish: true
  allow_failures:
    - env: SOLIDITY_COVERAGE=true
  include:
    - stage: tests
      name: "unit tests"
      script: npm run test
    - stage: coverage
      name: "unit tests with coverage"
      script: npm run test
      env: SOLIDITY_COVERAGE=true

